import base64
import os
import re
from pathlib import Path
from app.config import settings

TEMP_DIR = Path(settings.TEMP_DIR)
TEMP_DIR.mkdir(parents=True, exist_ok=True)


def parse_and_write_netscape_cookies(raw_cookies: str, output_path: str | Path, domain_keyword: str | None = None) -> str | None:
    """
    Parses a raw cookie string (which may be Base64-encoded, newline-escaped,
    or space-separated from copy-pasting into Render/Docker env vars)
    and writes it as a valid Netscape cookies.txt file.
    """
    if not raw_cookies or not raw_cookies.strip():
        return None

    cleaned = raw_cookies.strip()

    # Strip surrounding quotes if present
    if (cleaned.startswith('"') and cleaned.endswith('"')) or (cleaned.startswith("'") and cleaned.endswith("'")):
        cleaned = cleaned[1:-1].strip()

    # 1. Check if the string is Base64 encoded
    if not cleaned.startswith("#") and len(cleaned) > 20:
        try:
            decoded = base64.b64decode(cleaned, validate=True).decode("utf-8")
            if "# Netscape" in decoded or "\t" in decoded or "youtube" in decoded or "instagram" in decoded or "tiktok" in decoded:
                cleaned = decoded
        except Exception:
            pass

    # 2. Normalize escaped newlines
    cleaned = cleaned.replace("\\r\\n", "\n").replace("\\n", "\n").replace("\r\n", "\n")

    lines = cleaned.split("\n")
    valid_lines = []
    has_target_domain = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            valid_lines.append(stripped)
            continue

        # Check for tab delimiter vs whitespace delimiter
        parts = stripped.split("\t")
        if len(parts) < 7:
            # Attempt whitespace split (handles copy-paste tab-to-space conversions)
            parts = re.split(r"\s+", stripped, maxsplit=6)

        if len(parts) >= 7:
            domain, flag, path, secure, expiration, name, value = parts[:7]
            # Normalize booleans
            flag_val = "TRUE" if str(flag).upper() in ("TRUE", "1") else "FALSE"
            sec_val = "TRUE" if str(secure).upper() in ("TRUE", "1") else "FALSE"
            
            if domain_keyword:
                if domain_keyword.lower() in domain.lower():
                    has_target_domain = True
            else:
                has_target_domain = True

            valid_lines.append(f"{domain}\t{flag_val}\t{path}\t{sec_val}\t{expiration}\t{name}\t{value}")

    if not valid_lines:
        return None

    # If domain filtering was requested and none matched, return None
    if domain_keyword and not has_target_domain:
        return None

    out_file = Path(output_path)
    header = "# Netscape HTTP Cookie File\n# Generated by VideoSave\n"
    file_content = header + "\n".join(valid_lines) + "\n"

    try:
        out_file.parent.mkdir(parents=True, exist_ok=True)
        with open(out_file, "w", encoding="utf-8") as f:
            f.write(file_content)
        return str(out_file)
    except Exception:
        return None


def file_contains_domain(file_path: str, domain_keyword: str) -> bool:
    """Checks if a cookie file actually contains cookies for the given domain."""
    if not os.path.exists(file_path):
        return False
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                stripped = line.strip()
                if stripped and not stripped.startswith("#"):
                    if domain_keyword.lower() in stripped.lower():
                        return True
        return False
    except Exception:
        return False


def get_platform_cookie_file(
    platform: str,
    cookie_file_setting: str | None,
    cookie_env_raw: str | None,
    candidate_filenames: list[str] | None = None,
) -> str | None:
    """
    Finds or extracts a valid cookie file for a specific platform.
    Ensures that generic cookie files aren't mistakenly passed to platforms
    they don't support.
    """
    domain_map = {
        "youtube": "youtube.com",
        "tiktok": "tiktok.com",
        "instagram": "instagram.com",
        "vimeo": "vimeo.com",
    }
    target_domain = domain_map.get(platform.lower(), platform.lower())

    # 1. Explicit cookie file setting
    if cookie_file_setting and os.path.exists(cookie_file_setting):
        if file_contains_domain(cookie_file_setting, target_domain):
            return cookie_file_setting

    # 2. Raw cookie string in env vars
    if cookie_env_raw and cookie_env_raw.strip():
        tmp_path = TEMP_DIR / f"{platform}_cookies.txt"
        parsed = parse_and_write_netscape_cookies(cookie_env_raw, tmp_path, target_domain)
        if parsed:
            return parsed

    # 3. Candidate files on disk
    candidates = candidate_filenames or [f"{platform}_cookies.txt", "cookies.txt", "../cookies.txt"]
    for candidate in candidates:
        if os.path.exists(candidate) and file_contains_domain(candidate, target_domain):
            return candidate

    return None
